apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: luucasor/vollmed-api:1
        ports:
        - containerPort: 3000
        env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_DATABASE 
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados
              key: DB_HOST 